### ISSUE TITLE
Игнорировать папку "vendors"

### ISSUE THREAD

**Issue by vladimino** [alexand98/php-project-lvl2#1]
После установки проекта с помощью `composer install` в корневой директории создается папка `vendors` с пакетами сторонних разработчиков. Если сделать `git status` сразу после этого, то эта папка показывается как новая и доступная к добавлению в систему контроля версий. Правила хорошей организации PHP-приложений обязывают хранить в репозитории только код, который имеет непосредственное отношение к проекту, а все служебные файлы игнорировать. В этой задаче нужно добавить в репозиторий файл `.gitignore`, с помощью которого исключить папку `vendors` из списка доступных к добавлению.

**Comment by alexand98** [comment]
Файл .gitignore уже присутствует. Папка vendor исключена из списка доступных.
