### ISSUE TITLE
Переместить зависимость "squizlabs/php_codesniffer" в "require-dev" секцию

### ISSUE THREAD

**Issue by vladimino** [alexand98/php-project-lvl2#2]
Проверка стиля кода (codestyle) - это обязанность  исключительно окружения разработки, на продакшн-сервер тянуть эту зависимость совершенно ни к чему. Нужно изменить `composer.json` соответствующим образом.

**Comment by alexand98** [comment]
Изменил файл composer.json.
Переместил "squizlabs/php_codesniffer" в секцию "require-dev"
