### ISSUE TITLE
Исправить ошибки в стиле кода

### ISSUE THREAD

**Issue by vladimino** [alexand98/php-project-lvl2#3]
На данный момент проверка codestуle, встроенная в композер-скрипт под названием `phpcs`, завершается с ошибкой, находя 3 проблемы. Файл с выводом после запуска этой команды в приложении. В этой задаче нужно добиться того, чтоб на выходе было 0 ошибок, и в дальнейшем запускать эту команду перед публикацией любого следующего пулл-реквеста, чтоб сохранять чистоту стиля кода.

[phpcs-ouput.txt](https://github.com/alexand98/php-project-lvl2/files/3640109/phpcs-ouput.txt)

**Comment by alexand98** [comment]
Ошибки исправлены.
